Bloggerhead/Areas/Admin/Controllers/AuthController.cs
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Security.Claims;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using Bloggerhead.Admin.Models;
using Bloggerhead.Services;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;

namespace Bloggerhead.Admin.Controllers
{
    [Area("Admin")]
    public class AuthController : AuthBaseController
    {
        public AuthController(IHttpContextAccessor context, IUserService userService)
            : base(context, userService)
        {
            
        }

        public IActionResult Login()
        {
            var model = new LoginViewModel();
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Login(LoginViewModel model)
        {
            var user = userService.AuthenticateUser(model.UserName, model.Password);
            if(user != null)
            {
                var claims = new List<Claim>
                {
                    new Claim(ClaimTypes.Name, user.UserName),
                };

                var claimsIdentity = new ClaimsIdentity(
                    claims, CookieAuthenticationDefaults.AuthenticationScheme);

                var authProperties = new AuthenticationProperties
                {
                    IsPersistent = true
                };

                await context.HttpContext.SignInAsync(
                        CookieAuthenticationDefaults.AuthenticationScheme, 
                        new ClaimsPrincipal(claimsIdentity), 
                        authProperties);
                
                return RedirectToAction("Index", "Admin");
            }
            ViewData["ErrorMessage"] = "Invalid UserName/Password";
            return View(model);
        }

        public async Task<IActionResult> LogOut()
        {
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            return RedirectToAction("Login");
        }
    }
}

Bloggerhead/Areas/Admin/Controllers/PostsController.cs
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using Bloggerhead.Admin.Models;
using Bloggerhead.Services;
using Microsoft.Extensions.Options;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Linq;
using System.Text;

namespace Bloggerhead.Admin.Controllers
{
    [Area("Admin")]
    public class PostsController : AuthBaseController
    {
        private AppSettings appSettings;
        private IPostService postService;

        public PostsController(IHttpContextAccessor context, IUserService userService, IOptions<AppSettings> options, IPostService postService) 
            : base(context, userService)
        {
            this.appSettings = options.Value;
            this.postService = postService;
        }

        public IActionResult New()
        {
            if(!Authenticated())
            {
                return RedirectToAction("Login", "Auth");
            }

            var model = new PostModel();

            setViewData("Create");
            return View(model);
        }

        [HttpPost]
        public IActionResult New(PostModel model)
        {
            if(!Authenticated())
            {
                return RedirectToAction("Login", "Auth");
            }

            if(!ModelState.IsValid)
            {
                setViewData("Create");
                return View(model);
            }

            var slug = createSlugFromTitle(model.Title);
            var blurb = extractBlurb(model.Content);
            var post = postService.CreatePost(model.Title, model.Content, model.ImgUrl, model.Status, GetUser(), model.Tags.Split(","), blurb, slug);

            return RedirectToAction("Edit", new { id = post.Id });
        }

        public IActionResult Edit(int id)
        {
            if(!Authenticated())
            {
                return RedirectToAction("Login", "Auth");
            }

            var post = postService.GetPost(id);
            var tagStr = string.Join(',', postService.GetTags(post));

            var model = new PostModel
            {
                Title = post.Title,
                Content = post.Content,
                Id = post.Id,
                ImgUrl = post.ImgUrl,
                Status = post.Published? "Published" : "Draft",
                Tags =  tagStr
            };

            setViewData("Edit");
            return View("New", model);
        }

        [HttpPost]
        public IActionResult Edit(int id, PostModel model)
        {
            if(!ModelState.IsValid)
            {
                setViewData("Edit");
                return View(model);
            }

            var post = postService.GetPost(id);
            post.Title = model.Title;
            post.Content = model.Content;
            post.ImgUrl = model.ImgUrl;
            post.Published = model.Status == "Published";
            post.PublishedDate = DateTime.UtcNow;
            post.Blurb = extractBlurb(model.Content);
            post.Slug = createSlugFromTitle(model.Title);

            postService.SavePost(post); // Oh dear, I need to synchronise the tags here.

            return RedirectToAction("Edit", new { id = post.Id });
        }

        public IActionResult Published()
        {
            if(!Authenticated())
            {
                return RedirectToAction("Login", "Auth");
            }

            ViewData["Title"] = "Published Posts";
            var posts = postService.GetPublishedPostsByDateDesc();
            return View("Index", posts);
        }

        public IActionResult Drafts()
        {
            if(!Authenticated())
            {
                return RedirectToAction("Login", "Auth");
            }

            ViewData["Title"] = "Draft Posts";
            var posts = postService.GetDraftPostsByDateDesc();
            return View("Index", posts);
        }

        private void setViewData(string action)
        {
            var storageAccount = appSettings.AzureStorageAccount;
            var storageAccountKey = appSettings.AzureStorageAccountKey;
            var containerName = appSettings.AzureStorageContainer;

            ViewData["Action"] = action;
            ViewData["AzureContainerUrl"] = $"https://{storageAccount}.blob.core.windows.net/{containerName}";

            ViewBag.Statuses = new List<SelectListItem>
            {
                new SelectListItem {Text = "Draft", Value = "Draft"},
                new SelectListItem {Text = "Published", Value = "Published"},
            };
        }

        public static String sanitise(string input)
        {
            const string removeChars = "?/&^$#@!,:;<>’\'*";
            var sb = new StringBuilder(input.Length);
            foreach (char x in input.Where(c => !removeChars.Contains(c)))
            {
                sb.Append(x);
            }
            return sb.ToString();
        }

        private static string createSlugFromTitle(string title)
        {
            title = sanitise(title);
            if(string.IsNullOrEmpty(title))
            {
                return "";
            }

            if(title.Length > 40)
            {
                return title.Substring(0, 40).ToLower().Replace(" ", "-");
            }

            return title.ToLower().Replace(" ", "-");
        }

        
        private static string extractBlurb(string content)
        {
            if(string.IsNullOrEmpty(content))
            {
                return string.Empty;
            }

            var indexOfBr = content.IndexOf("<br>"); // as a very basic burb extractor - just use the first paragraph;

            if(indexOfBr > 0)
            {
                var firstParagraph = content.Substring(0, indexOfBr - 1);
                return $"{firstParagraph}</div>"; // append a closing div since trix editor wraps the content in divs.
            }

            return content;
        }

    }
}

Bloggerhead/Areas/Admin/Controllers/ProfileController.cs
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using Bloggerhead.Admin.Models;
using Bloggerhead.Services;
using Microsoft.Extensions.Options;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Linq;
using System.Text;

namespace Bloggerhead.Admin.Controllers
{
    [Area("Admin")]
    public class ProfileController : AuthBaseController
    {
        public ProfileController(IHttpContextAccessor context, IUserService userService) 
            : base(context, userService)
        {

        }

        public IActionResult Index()
        {
            if(!Authenticated())
            {
                return RedirectToAction("Login", "Auth");
            }

            var user = GetUser();

            var userModel = new UserViewModel{
                Id = user.Id,
                FirstName = user.FirstName,
                Surname = user.Surname,
                EmailAddress = user.Email,
                UserName = user.UserName
            };
            return View(userModel);
        }

        [HttpPost]
        public IActionResult Index(UserViewModel model)
        {
            if(!Authenticated())
            {
                return RedirectToAction("Login", "Auth");
            }

            if(!ModelState.IsValid)
            {
                return View(model);
            }

            var user = GetUser();
            user.FirstName = model.FirstName;
            user.Surname = model.Surname;
            user.Email = model.EmailAddress;
            
            userService.SaveUser(user);

            return RedirectToAction("Index");
        }

    }
}

Bloggerhead/Areas/Admin/Controllers/SettingsController.cs
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using Bloggerhead.Admin.Models;
using Bloggerhead.Services;
using Microsoft.Extensions.Options;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Linq;
using System.Text;

namespace Bloggerhead.Admin.Controllers
{
    [Area("Admin")]
    public class SettingsController : AuthBaseController
    {
        private ISettingsService settingsService;
        private AppSettings appSettings;

        public SettingsController(IHttpContextAccessor context, IUserService userService, ISettingsService settingsService, IOptions<AppSettings> options) 
            : base(context, userService)
        {
            this.settingsService = settingsService;
            this.appSettings = options.Value;
        }

        public IActionResult Edit()
        {
            if(!Authenticated())
            {
                return RedirectToAction("Login", "Auth");
            }

            var settings = settingsService.GetSettings();

            var model = new SettingsModel
            {
                BlogTitle = settings.BlogTitle,
                BlogDesc = settings.BlogDesc,
                BackgroundImgUrl = settings.BackgroundImgUrl,
                InitialPostCount = settings.InitialPostCount,
                LoadMorePostsCount = settings.LoadMorePostsCount
            };

            setViewData();
            return View(model);
        }

        [HttpPost]
        public IActionResult Edit(SettingsModel model)
        {
            if(!Authenticated())
            {
                return RedirectToAction("Login", "Auth");
            }

            if(!ModelState.IsValid)
            {
                setViewData();
                return View(model);
            }

            var settings = settingsService.GetSettings();
            settings.BlogTitle = model.BlogTitle;
            settings.BlogDesc = model.BlogDesc;
            settings.BackgroundImgUrl = model.BackgroundImgUrl;
            settings.InitialPostCount = model.InitialPostCount;
            settings.LoadMorePostsCount = model.LoadMorePostsCount;

            settingsService.SaveSettings(settings);

            return RedirectToAction("Edit");
        }


        private void setViewData()
        {
            var storageAccount = appSettings.AzureStorageAccount;
            var storageAccountKey = appSettings.AzureStorageAccountKey;
            var containerName = appSettings.AzureStorageContainer;

            ViewData["AzureContainerUrl"] = $"https://{storageAccount}.blob.core.windows.net/{containerName}";
        }
    }
}

Bloggerhead/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>@ViewData["Title"] - Bloggerhead Admin</title>
    <link href="~/lib/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/css/sb-admin-2.css" rel="stylesheet">
    <link href="~/lib/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
    <link href="~/css/site-admin.css" rel="stylesheet">
    @RenderSection("AdditionalHead", required: false)
</head>
<body>
    <div id="wrapper">
        <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" asp-area="Admin" asp-controller="Admin" asp-action="Index">Bloggerhead</a>
            </div>
            <ul class="nav navbar-top-links navbar-right">
                <li>
                     <a class="" href="/" target="_blank">View Site <i class="fa fa-external-link"></i></a>
                </li>
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <i class="fa fa-bell fa-fw"></i> <i class="fa fa-caret-down"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-alerts">
                        <li>
                            <a href="#">
                                <div>
                                    <i class="fa fa-comment fa-fw"></i> New Post
                                    <span class="pull-right text-muted small">4 minutes ago</span>
                                </div>
                            </a>
                        </li>
                    </ul>
                </li>
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <i class="fa fa-user fa-fw"></i> <i class="fa fa-caret-down"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-user">
                        <li>
                            <a asp-area="Admin" asp-controller="Profile" asp-action="Index"><i class="fa fa-user fa-fw"></i> User Profile</a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a asp-area="Admin" asp-controller="Auth" asp-action="Logout"><i class="fa fa-sign-out fa-fw"></i> Logout</a>
                        </li>
                    </ul>
                </li>
            </ul>
            <div class="navbar-default sidebar" role="navigation">
                <div class="sidebar-nav navbar-collapse">
                    <ul class="nav" id="side-menu">
                        <li class="sidebar-search">
                            <div class="input-group custom-search-form">
                                <input type="text" class="form-control" placeholder="Search...(not implemented)">
                                <span class="input-group-btn">
                                <button class="btn btn-default" type="button">
                                    <i class="fa fa-search"></i>
                                </button>
                            </span>
                            </div>
                        </li>
                        <li>
                            <a asp-area="Admin" asp-controller="Admin" asp-action="Index"><i class="fa fa-table fa-fw"></i> Posts</a>
                            <ul class="nav nav-second-level">
                                <li>
                                    <a asp-area="Admin" asp-controller="Posts" asp-action="Published">Published</a>
                                </li>
                                <li>
                                    <a asp-area="Admin" asp-controller="Posts" asp-action="Drafts">Drafts</a>
                                </li>
                            </ul>
                        </li>
                        <li>
                            <a asp-area="Admin" asp-controller="Settings" asp-action="Edit"><i class="fa fa-dashboard fa-fw"></i> Settings</a>
                        </li>                        
                    </ul>
                </div>
            </div>
        </nav>

        <div id="page-wrapper">
            <div class="row">
                <div class="col-lg-12">
                    <h1 class="page-header">@ViewData["Title"]</h1>
                </div>
            </div>
            @RenderBody()
        </div>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/js/bootstrap.min.js"></script>
    <script src="~/js/sb-admin-2.js"></script>
    @RenderSection("Scripts", required: false)
</body>

</html>